job_base: &job_base
  docker:
    - image: circleci/node:8.11.3

  working_directory: ~/repo

version: 2
jobs:
  general:
    <<: *job_base
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Jest Test
          command: yarn test

      - run:
          name: Type check
          command: yarn tsc

      - run:
          name: TSLint
          command: yarn lint

  deploy:
    <<: *job_base
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: yarn install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: expo login
          command: ./node_modules/.bin/exp login -u "$EXPO_ACCOUNT" -p "$EXPO_PASSWORD"

      - run:
          name: create .env
          command: echo API_TOKEN=$API_TOKEN >> .env

      - run:
          name: expo publish
          command: ./node_modules/.bin/exp publish

workflows:
  version: 2
  general_deploy:
    jobs:
      - general
      - deploy:
          requires:
            - general
          filters:
            branches:
              only:
                - /master/
